In [2]:
# solve system of lenear equations

In [1]:
import numpy as np

In [5]:
A = [[1, 2], [2,3]]
B = [0, 1]

In [6]:
A, B

([[1, 2], [2, 3]], [0, 1])

In [8]:
X = np.linalg.solve(A, B)
X

array([ 2., -1.])

In [11]:
m1 = [[2, 1], [1, 2]]
k1 = [7, 8]
m1, k1

([[2, 1], [1, 2]], [7, 8])

In [12]:
x1 = np.linalg.solve(m1, k1)
x1

array([2., 3.])

In [13]:
m2 = [[3, 2], [2, 3]]
k2 = [180, 170]
m2, k2

([[3, 2], [2, 3]], [180, 170])

In [14]:
x2 = np.linalg.solve(m2, k2)
x2

array([40., 30.])

Kazahstan problem

In [2]:
m = [[1, 1, 0], [1, 0, 1], [-1, 0, 1]]
y = [8, 13, 6]
x = np.linalg.solve(m, y)
x

array([3.5, 4.5, 9.5])

In [3]:
m = [[1, 1, 0], [1, 0, 1], [-1, 0, 1]]
y = [16, 26, 12]
x = np.linalg.solve(m, y)
x

array([ 7.,  9., 19.])

In [9]:
m = [[1, 1, 0, 0], [0, 0, 1, -1], [1, 0, 1, 0], [0, 1, 0, 1]]
y = [16, 12, 26, 16]
x = np.linalg.solve(m, y)
x

array([ 7.,  9., 19.,  7.])